name: Vue build 
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: VUE_APP_API_URL=${CORE} VUE_APP_FILE_API_URL=${FILE} yarn build
        env:
          CORE: ${{ secrets.VUE_APP_API_URL }}
          FILE: ${{ secrets.VUE_APP_FILE_API_URL }}
        
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://s3-2-frame

